# Generated by Django 4.2.6 on 2023-11-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sureName", models.CharField(max_length=100)),
                ("documento", models.IntegerField()),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("NR", "No responde"),
                        ],
                        max_length=100,
                    ),
                ),
                ("ficha", models.IntegerField()),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
            ],
        ),
    ]
